column_map = {
    "p1": {"name": "id_nehody", "mapping": {}},
    "p2a": {"name": "datum", "mapping": {}},
    "p2b": {"name": "cas", "mapping": {}},
    "p4a": {"name": "kraj", "mapping": {}},
    "p4b": {"name": "okres", "mapping": {}},
    "p5a": {
        "name": "lokalita",
        "mapping": {
            "1": "v obci",
            "2": "mimo obce",
        },
    },
    "p6": {
        "name": "druh_nehody",
        "mapping": {
            1: "srazka_jedouci_nekolejove",
            2: "srazka_zaparkovane",
            3: "srazka_pevna_prekazka",
            4: "srazka_chodec",
            5: "srazka_lesni_zver",
            6: "srazka_domaci_zvire",
            7: "srazka_vlak",
            8: "srazka_tramvaj",
            9: "havarie",
            0: "jiny_druh_nehody",
        },
    },
    "p7": {
        "name": "druh_srazky_vozidel",
        "mapping": {
            1: "celni",
            2: "bocni",
            3: "z_boku",
            4: "zezadu",
            0: "neprichazi_v_uvahu",
        },
    },
    "p8": {
        "name": "prekazka",
        "mapping": {
            1: "strom",
            2: "sloup",
            3: "odraznik_patnik",
            4: "svodidlo",
            5: "prekazka_provoz_jine_vozidlo",
            6: "zdi_pevne_casti",
            7: "zavory",
            8: "prekazka_stavebni_cinnost",
            9: "jina_prekazka",
            0: "neprichazi_v_uvahu",
        },
    },
    "p8a": {
        "name": "druh_zvirete",
        "mapping": {
            1: "srna",
            2: "jelen",
            3: "danek",
            4: "muflon",
            5: "zajic",
            6: "bazant",
            7: "divoke_prase",
            8: "liska",
            9: "sob",
            10: "vlk",
            11: "medved",
            12: "jina_zver",
            13: "vepr",
            14: "krava",
            15: "kun",
            16: "koza",
            17: "ovce",
            18: "pes",
            19: "kocka",
            20: "slepice",
            21: "kachna",
            22: "jine_zvire",
            0: "nejde_o_srazku",
        },
    },
    "p9": {
        "name": "charakter",
        "mapping": {1: "s_nasledky_na_zivote", 2: "pouze_hmotna_skoda"},
    },
    "p10": {
        "name": "zavineni",
        "mapping": {
            1: "ridicem_motoroveho",
            2: "ridicem_nemotoroveho",
            3: "chodcem",
            4: "zver_domaci",
            5: "jiny_ucastnik",
            6: "zavadou_komunikace",
            7: "technicka_zavada",
            0: "jine",
        },
    },
    "p11": {
        "name": "alkohol",
        "mapping": {
            1: "ano",
            2: "ne",
            3: "ano",
            4: "odmitnuto",
            5: "ano",
            6: "ano",
            7: "ano",
            8: "ano",
            9: "ano",
            0: "nezjistovano",
        },
    },
    "p11a": {
        "name": "drogy",
        "mapping": {
            1: "THC",
            2: "AMP",
            3: "MET",
            4: "OPI",
            5: "benzodiazepin",
            6: "jine",
            7: "odmitnuto",
            8: "nezjistovano",
            0: "ne",
        },
    },
    "p12": {
        "name": "hlavni_pricina",
        "mapping": {
            100: "nezavinena_ridicem",
            201: "neprimerena_rychlost_intenzita",
            202: "neprimerena_rychlost_viditelnost",
            203: "neprimerena_rychlost_vlastnosti",
            204: "neprimerena_rychlost_stav_vozovky",
            205: "neprimerena_rychlost_dopravni_stav",
            206: "prekroceni_rychlosti_pravidla",
            207: "prekroceni_rychlosti_znacka",
            208: "neprimerena_rychlost_vitr",
            209: "jiny_druh_rychlosti",
            301: "predjizdeni_vpravo",
            302: "predjizdeni_bez_odstupu",
            303: "predjizdeni_bez_rozhledu",
            304: "predjizdeni_ohrozeni_protijedouci",
            305: "predjizdeni_ohrozeni_predjizdeny",
            306: "predjizdeni_vlevo",
            307: "predjizdeni_zakazano",
            308: "predjizdeni_prejeta_cara",
            309: "braneni_predjizdeni",
            310: "prehlednuti_predjizdeni",
            311: "jiny_druh_predjizdeni",
            401: "nedani_prednosti_cervena",
            402: "nedani_prednosti_stuj_dej_prednost",
            403: "nedani_prednosti_dej_prednost",
            404: "nedani_prednosti_zprava",
            405: "nedani_prednosti_odbočení_vlevo",
            406: "nedani_prednosti_tramvaj",
            407: "nedani_prednosti_objizdeni",
            408: "nedani_prednosti_zarazovani",
            409: "nedani_prednosti_vjezd",
            410: "nedani_prednosti_otaceni",
            411: "nedani_prednosti_pruhy",
            412: "nedani_prednosti_chodec",
            413: "nedani_prednosti_odbočení_souběh",
            414: "jiny_druh_prednosti",
            501: "jizda_protismer",
            502: "vyhybani_bez_odstupu",
            503: "nedodrzeni_vzdalenosti",
            504: "otaceni_couvani",
            505: "chyby_smer",
            506: "agresivni_jizda",
            507: "zabrzdeni",
            508: "nevenovani_rizeni",
            509: "nezajistene_vozidlo",
            510: "nezpevnena_komunikace",
            511: "nezvladnuti_rizeni",
            512: "jizda_jednosmerka",
            513: "nehoda_nasilne_zastaveni",
            514: "nehoda_sluzebni_zbran",
            515: "nehoda_sluzebni_zakrok",
            516: "jiny_druh_jizdy",
            601: "zavada_rizeni",
            602: "zavada_brzdy",
            603: "nefunkcni_parkovaci_brzda",
            604: "opotrebena_pneumatika",
            605: "defekt_pneumatiky",
            606: "zavada_osvetleni",
            607: "nepripojena_hadice",
            608: "nespravne_naklad",
            609: "ztrata_kola",
            610: "zablokovana_kola",
            611: "lom_pruziny",
            612: "nezajistena_bocnice",
            613: "zavada_zavesu",
            614: "utrzeni_hridel",
            615: "jina_zavada",
        },
    },
    "p13a": {"name": "usmrceno_osob", "mapping": {}},
    "p13b": {"name": "tezce_zraneno_osob", "mapping": {}},
    "p13c": {"name": "lehce_zraneno_osob", "mapping": {}},
    "p14": {"name": "celkova_skoda", "mapping": {}},
    "p15": {
        "name": "druh_povrchu_voz",
        "mapping": {
            1: "dlazba",
            2: "zivice",
            3: "beton",
            4: "panely",
            5: "sterk",
            6: "nezpevneny",
        },
    },
    "p16": {
        "name": "stav_povrchu_voz",
        "mapping": {
            1: "suchy",
            2: "suchy_znecisteny",
            3: "mokry",
            4: "blato",
            5: "naled_posypane",
            6: "naled_neposypane",
            7: "rozlity_olej",
            8: "snehova_vrstva",
            9: "nahla_zmena",
            0: "jiny_stav",
        },
    },
    "p17": {
        "name": "stav_vozovky",
        "mapping": {
            1: "dobry_bez_zavad",
            2: "sklon_vyssi",
            3: "chybejici_znacka",
            4: "zvlneny_povrch",
            5: "souvisle_vytluky",
            6: "nesouvisle_vytluky",
            7: "trvale_zuseni",
            8: "hrbol",
            9: "neoznacena_prekazka",
            10: "prechodna_uzavirka_jizdniho_pruhu",
            11: "uzavirka_jizdniho_pasu",
            12: "jiny_stav",
        },
    },
    "p18": {
        "name": "povetrnostni_podm",
        "mapping": {
            1: "neztizene",
            2: "mlha",
            3: "slaby_dest",
            4: "dest",
            5: "snezeni",
            6: "naled",
            7: "narazovy_vitr",
            0: "jine",
        },
    },
    "p19": {
        "name": "viditelnost",
        "mapping": {
            1: "ve_dne_bez_zmen",
            2: "svitani_soumrak",
            3: "povetrnostni_vliv",
            4: "v_noci_verejne_osvetleni",
            5: "v_noci_verejne_zmena",
            6: "v_noci_bez_osvetleni",
            7: "v_noci_bez_osvetleni_zmena",
        },
    },
    "p20": {
        "name": "rozhled",
        "mapping": {
            1: "dobre",
            2: "zastavba",
            3: "prubeh_komunikace",
            4: "vegetace_trvale",
            5: "vegetace_docasne",
            6: "zakryty_vyhled",
            0: "jine",
        },
    },
    "p21": {
        "name": "deleni_komun",
        "mapping": {
            1: "dvoupruhova",
            2: "tripruhova",
            3: "ctyrpruhova_pasem",
            4: "ctyrpruhova_carou",
            5: "vicepruhova",
            6: "rychlostni",
            0: "zadna",
        },
    },
    "p22": {
        "name": "situovani",
        "mapping": {
            1: "jizdni_pruh",
            2: "odstavny_pruh",
            3: "krajnice",
            4: "odbocovaci_pruh",
            5: "pomaly_pruh",
            6: "chodnik",
            7: "koleje",
            8: "mimo_komunikaci",
            9: "stezka_cyklisty",
            0: "zadne",
        },
    },
    "p23": {
        "name": "rizeni_provozu_v_dobe_nehody",
        "mapping": {
            1: "policistou_nebo_jinym_poverenym_organem",
            2: "svetelnym_signalizacnim_zarizenim",
            3: "mistni_uprava",
            0: "zadny_zpusob_rizeni_provozu",
        },
    },
    "p24": {
        "name": "mistni_uprava_prednosti_v_jizde",
        "mapping": {
            1: "svetelna_signalizace_na_prerusovanou_zlutou",
            2: "svetelna_signalizace_mimo_provoz",
            3: "prednost_vyznačena_dopravnimi_znackami",
            4: "prednost_vyznačena_prenosnymi_znackami",
            5: "prednost_nevyznacena_pravidla_silnicniho_provozu",
            0: "zadna_mistni_uprava",
        },
    },
    "p27": {
        "name": "specificka_mista_a_objekty_v_miste_nehody",
        "mapping": {
            1: "prechod_pro_chodce",
            2: "v_blizkosti_prechodu_pro_chodce",
            3: "zeleznicni_prejezd_nezabezpeceny",
            4: "zeleznicni_prejezd_zabezpeceny",
            5: "most_nadjezd_podjezd_tunel",
            6: "zastavka_s_nastupnim_ostruvkem",
            7: "zastavka_bez_nastupniho_ostruvku",
            8: "vyjezd_z_parkoviste_lesni_cesty",
            9: "cerpadlo_pohonnych_hmot",
            10: "parkoviste_prilehajici_ke_komunikaci",
            0: "zadne_nebo_zadne_z_uvedenych",
        },
    },
    "p28": {
        "name": "smerove_pomery",
        "mapping": {
            1: "primy_usek",
            2: "primy_usek_po_projeti_zatackou",
            3: "zatacka",
            4: "krizovatka_prusecna_ctyrzramenna",
            5: "krizovatka_stykova_tri_ramena",
            6: "krizovatka_peti_a_vice_ramennych",
            7: "kruhovy_objezd",
        },
    },
    "p29": {
        "name": "kategorie_chodce",
        "mapping": {
            1: "muz",
            2: "zena",
            3: "dite_do_15_let",
            4: "skupina_deti",
            5: "jina_skupina",
        },
    },
    "p29a": {"name": "reflexni_prvky_u_chodce", "mapping": {1: "ano", 2: "ne"}},
    "p29b": {"name": "chodec_na_osobnim_prepravniku", "mapping": {1: "ano", 2: "ne"}},
    "p30": {
        "name": "stav_chodce",
        "mapping": {
            1: "dobry",
            2: "nepozornost_roztrzitost",
            3: "pod_vlivem_leku_narkotik",
            4: "nezadano",
            5: "fyzicka_indispozice",
            6: "pokus_o_sebevrazdu",
            7: "invalida",
            8: "jiny_neuvedeny_stav",
            9: "nezadano",
            0: "nezjisteno",
        },
    },
    "p30a": {
        "name": "alkohol_u_chodce_pritomen",
        "mapping": {
            1: "ano_do_0_24",
            2: "ne",
            3: "ano_0_24_0_5",
            4: "odmitnuto",
            5: "nezadano",
            6: "ano_0_5_0_8",
            7: "ano_0_8_1_0",
            8: "ano_1_0_1_5",
            9: "ano_1_5_a_vice",
            0: "nezjistovano",
        },
    },
    "p30b": {
        "name": "druh_drogy_u_chodce",
        "mapping": {
            1: "thc",
            2: "amp",
            3: "met",
            4: "opi",
            5: "benzodiazepin",
            6: "jine",
            7: "odmitnuto",
            8: "nezjistovano",
            0: "ne",
        },
    },
    "p34": {"name": "pocet_vozidel", "mapping": {}},
    "p35": {
        "name": "misto_nehody",
        "mapping": {
            0: "mimo_krizovatku",
            10: "na_krizovatce_mistnich_komunikaci",
            11: "uvnitr_zony_1",
            18: "uvnitr_zony_8",
            19: "na_krizovatce_v_ramci_systemu",
            22: "na_vjezdove_casti_mimourovne",
            28: "na_vyjezdove_casti_mimourovne",
            29: "mimo_zonu_11_19_a_22_28",
        },
    },
    "p36": {
        "name": "druh_komun",
        "mapping": {
            0: "dalnice",
            1: "silnice_1_tridy",
            2: "silnice_2_tridy",
            3: "silnice_3_tridy",
            4: "uzel",
            5: "komunikace_sledovana",
            6: "komunikace_mistni",
            7: "komunikace_ucelova_pole_les",
            8: "komunikace_ucelova_ostatni",
        },
    },
    "p37": {"name": "cislo_pozemni_komunikace", "mapping": {}},
    "p39": {
        "name": "druh_krizujici_komunikace",
        "mapping": {
            1: "silnice_1_tridy",
            2: "silnice_2_tridy",
            3: "silnice_3_tridy",
            6: "mistni_komunikace",
            7: "ucelova_komunikace",
            9: "vetev_mimourovnove_krizovatky",
        },
    },
    "p44": {
        "name": "druh_vozidla",
        "mapping": {
            2: "motocykl",
            3: "osobni_automobil_bez_privesu",
            4: "osobni_automobil_s_privesem",
            5: "nakladni_automobil",
            6: "nakladni_automobil_s_privesem",
            7: "nakladni_automobil_s_navesem",
            8: "autobus",
            9: "traktor",
            10: "tramvaj",
            11: "trolejbus",
            12: "jine_motorove_vozidlo",
            13: "jizdni_kolo",
            14: "povoz",
            15: "jine_nemotorove_vozidlo",
            16: "vlak",
            17: "nezjisteno",
            18: "jiny_druh_vozidla",
            19: "kolobezka",
        },
    },
    "p45a": {
        "name": "vyrobni_znacka_motoroveho_vozidla",
        "mapping": {
            1: "alfa_romeo",
            2: "audi",
            3: "avia",
            4: "bmw",
            5: "chevrolet",
            6: "chrysler",
            7: "citroen",
            8: "dacia",
            9: "daewoo",
            10: "daf",
            11: "dodge",
            12: "fiat",
            13: "ford",
            14: "gaz_volha",
            15: "ferrari",
            16: "honda",
            17: "hyundai",
            18: "ifa",
            19: "iveco",
            20: "jaguar",
            21: "jeep",
            22: "lancia",
            23: "land_rover",
            24: "liaz",
            25: "mazda",
            26: "mercedes",
            27: "mitsubishi",
            28: "moskvic",
            29: "nissan",
            30: "oltcit",
            31: "opel",
            32: "peugeot",
            33: "porsche",
            34: "praga",
            35: "renault",
            36: "rover",
            37: "saab",
            38: "seat",
            39: "skoda",
            40: "scania",
            41: "subaru",
            42: "suzuki",
            43: "tatra",
            44: "toyota",
            45: "trabant",
            46: "vaz",
            47: "volkswagen",
            48: "volvo",
            49: "wartburg",
            50: "zastava",
            51: "agm",
            52: "aro",
            53: "austin",
            54: "barkas",
            55: "daihatsu",
            56: "datsun",
            57: "destacar",
            58: "isuzu",
            59: "karosa",
            60: "kia",
            61: "lublin",
            62: "man",
            63: "maserati",
            64: "multicar",
            65: "pontiac",
            66: "ross",
            67: "simca",
            68: "ssangyong",
            69: "talbot",
            70: "taz",
            71: "zaz",
            72: "bova",
            73: "ikarus",
            74: "neoplan",
            75: "oasa",
            76: "raf",
            77: "setra",
            78: "sor",
            79: "aprilia",
            80: "cagiva",
            81: "cz",
            82: "derbi",
            83: "ducati",
            84: "gilera",
            85: "harley",
            86: "hero",
            87: "husqvarna",
            88: "jawa",
            89: "kawasaki",
            90: "ktm",
            91: "malaguti",
            92: "manet",
            93: "mz",
            94: "piaggio",
            95: "simson",
            96: "velorex",
            97: "yamaha",
            98: "jine_vyrobene_v_cr",
            99: "jine_vyrobene_mimo_cr",
            0: "zadna_z_uvedenych",
        },
    },
    "p47": {"name": "rok_vyroby_vozidla", "mapping": {}},
    "p48a": {
        "name": "charakteristika_vozidla",
        "mapping": {
            1: "soukromé - nevyužívané k výdělečné činnosti",
            2: "soukromé - využívané k výdělečné činnosti",
            3: "soukromá organizace",
            4: "veřejná hromadná doprava",
            5: "městská hromadná doprava",
            6: "mezinárodní kamionová doprava",
            7: "TAXI",
            8: "státní podnik, státní organizace",
            9: "registrované mimo území ČR",
            10: "zastupitelský úřad",
            11: "ministerstvo vnitra",
            12: "policie ČR",
            13: "městská, obecní policie",
            14: "soukromé bezpečnostní agentury",
            15: "ministerstvo obrany",
            16: "jiné",
            17: "odcizené",
            18: "vozidlo AUTOŠKOLY provádějící výcvik",
            19: "hasiči",
            20: "sanita RZS",
            21: "sanita ostatní (ne RZS)",
            0: "nezjištěno",
        },
    },
    "p49": {"name": "smyk", "mapping": {1: "ano", 0: "ne"}},
    "p50a": {
        "name": "vozidlo_po_nehode",
        "mapping": {
            1: "nedošlo k požáru",
            2: "došlo k požáru",
            3: "řidič ujel - zjištěn",
            4: "řidič ujel (utekl) - nezjištěn",
            0: "žádná z uvedených",
        },
    },
    "p50b": {
        "name": "unik_provoznich_prepravovanych_hmot",
        "mapping": {
            1: "došlo k úniku pohonných hmot, oleje, chladícího média apod.",
            2: "došlo k úniku jiných nebezpečných látek - pevných",
            3: "došlo k úniku jiných nebezpečných látek - kapalných",
            4: "došlo k úniku jiných nebezpečných látek - plynných",
            0: "žádné z uvedených",
        },
    },
    "p51": {
        "name": "zpusob_vyprosteni_osob_z_vozidla",
        "mapping": {
            1: "nebylo třeba užít násilí",
            2: "použitím páčidel apod.",
            3: "použitím speciální vyprošťovací techniky",
        },
    },
    "p52": {
        "name": "smer_jizdy_nebo_postaveni_vozidla",
        "mapping": {
            1: "vozidlo jedoucí - ve měru staničení (na komunikaci)",
            2: "vozidlo odstavené, parkující - ve směru staničení (na komunikaci)",
            3: "vozidlo jedoucí - proti směru staničení (na komunikaci)",
            4: "vozidlo odstavené, parkující - proti směru staničení (na komunikaci)",
            5: "vozidlo jedoucí - na komunikaci bez staničení",
            6: "vozidlo odstavené, parkující - na komunikaci bez staničení",
            "10-99": "zachycuje postavení vozidla při nehodě na křižovatce",
        },
    },
    "p55a": {
        "name": "kategorie_ridice",
        "mapping": {
            1: "s řidičským oprávněním skupiny A",
            2: "s řidičským oprávněním skupiny B",
            3: "s řidičským oprávněním skupiny C",
            4: "s řidičským oprávněním skupiny D",
            5: "s řidičským oprávněním skupiny T",
            6: "s řidičským oprávněním skupiny A a s omezením do 50 ccm",
            7: "bez příslušného řidičského oprávnění",
            8: "ostatní řidiči vozidel",
            9: "nezjištěno, řidič místo nehody opustil",
            0: "nezjištěno",
        },
    },
    "p57": {
        "name": "stav_ridice",
        "mapping": {
            1: "dobrý - žádné nepříznivé okolnosti nebyly zjištěny",
            21: "unaven, usnul",
            22: "náhlá fyzická indispozice",
            3: "pod vlivem léků, narkotik",
            4: "pod vlivem alkoholu, obsah alkoholu v krvi do 0,99 ‰",
            5: "pod vlivem alkoholu, obsah alkoholu v krvi 1 ‰ a více",
            6: "nemoc, úraz apod.",
            7: "invalida",
            8: "řidič při jízdě zemřel",
            9: "pokus o sebevraždu, sebevražda",
            0: "jiný nepříznivý stav",
        },
    },
    "p58": {
        "name": "vnejsi_ovlivneni_ridice",
        "mapping": {
            1: "řidič nebyl ovlivněn",
            2: "oslněn sluncem",
            3: "oslněn světlomety jiného vozidla",
            4: "ovlivněn jednáním jiného účastníka silničního provozu",
            5: "ovlivněn při vyhýbání lesní zvěří, domácímu zvířectvu apod.",
            0: "jiné ovlivnění",
        },
    },
    "p59g": {
        "name": "nasledky",
        "mapping": {
            1: "usmrcení",
            2: "těžké zranění",
            3: "lehké zranění",
            4: "bez zranění",
        },
    },
    "x": {"name": "x", "mapping": {}},
    "y": {"name": "y", "mapping": {}},
}

column_mapping = {
    key: {
        "name": value["name"],
        "mapping": {str(k): v for k, v in value["mapping"].items()},
    }
    for key, value in column_map.items()
}
