type Accident = {
  attributes: {
    id_nehody: number;
    datum?: string;
    cas?: string | null;
    kraj?: string | null;
    okres?: string | null;
    lokalita?: string | null;
    druh_nehody?: string | null;
    druh_srazky_vozidel?: string | null;
    prekazka?: string | null;
    druh_zvirete?: string | null;
    charakter?: string | null;
    zavineni?: string | null;
    alkohol?: string | null;
    drogy?: string | null;
    hlavni_pricina?: string | null;
    usmrceno_osob?: number | null;
    tezce_zraneno_osob?: number | null;
    lehce_zraneno_osob?: number | null;
    celkova_skoda?: number | null;
    druh_povrchu_voz?: string | null;
    stav_povrchu_voz?: string | null;
    stav_vozovky?: string | null;
    povetrnostni_podm?: string | null;
    viditelnost?: string | null;
    rozhled?: string | null;
    deleni_komun?: string | null;
    situovani?: string | null;
    rizeni_provozu_v_dobe_nehody?: string | null;
    mistni_uprava_prednosti_v_jizde?: string | null;
    specificka_mista_a_objekty_v_miste_nehody?: string | null;
    smerove_pomery?: string | null;
    kategorie_chodce?: string | null;
    reflexni_prvky_u_chodce?: string | null;
    chodec_na_osobnim_prepravniku?: string | null;
    stav_chodce?: string | null;
    alkohol_u_chodce_pritomen?: string | null;
    druh_drogy_u_chodce?: string | null;
    pocet_vozidel?: number | null;
    misto_nehody?: string | null;
    druh_komun?: string | null;
    cislo_pozemni_komunikace?: string | null;
    druh_krizujici_komunikace?: string | null;
    druh_vozidla?: string | null;
    vyrobni_znacka_motoroveho_vozidla?: string | null;
    rok_vyroby_vozidla?: number | null;
    charakteristika_vozidla?: string | null;
    smyk?: string | null;
    vozidlo_po_nehode?: string | null;
    unik_provoznich_prepravovanych_hmot?: string | null;
    zpusob_vyprosteni_osob_z_vozidla?: string | null;
    smer_jizdy_nebo_postaveni_vozidla?: string | null;
    kategorie_ridice?: string | null;
    stav_ridice?: string | null;
    vnejsi_ovlivneni_ridice?: string | null;
    nasledky?: string | null;
    waze_matches_count: number;
    matched_waze: string[];
  };
  geometry: {
    x: number;
    y: number;
  };
};
